# Constants defining initial checkbox states for each job
JOB_DEFAULT_STATES = {
    "Request": True,
    "Donate": False,
    "Buy shop offers": True,
    "Upgrade your deck": True,
    "Buy from the season shop": False,
    "Open chests": True,
    "Collect battlepass": False,
    "Colled card mastery": True,
    "Collect daily rewards": False,
    "Collect level up chest": True,
    "Collect Bannerbox": False,
    "Collect Trophy Rewards": True,
    "Fight trophy road battle": False,
    "Fight goblin queen battle": True,
    "Fight path of legends battle": False,
    "Fight 2v2 battle": True,
    "Fight war battle": False,
    "Randomize deck": True,
    "Random plays": False,
    "Disable win/loss tracking": True,
    "Skip fighting when full chests": False,
}
tabName2jobList = {  # (job_name, toggle_name, increment_name)
    "Card Jobs": [
        ("Request", "request_toggle", "request_increment"),
        ("Donate", "donate_toggle", "donate_increment"),
        ("Buy shop offers", "shop_offers_toggle", "shop_offers_increment"),
        ("Upgrade your deck", "upgrade_deck_toggle", "upgrade_deck_toggle"),
        ("Buy from the season shop", "season_shop_toggle", "season_shop_toggle"),
    ],
    "Rewards Jobs": [
        ("Open chests", "open_chests_toggle", "open_chests_increment"),
        ("Collect battlepass", "battlepass_toggle", "battlepass_increment"),
        ("Colled card mastery", "mastery_toggle", "mastery_increment"),
        ("Collect daily rewards", "daily_toggle", "daily_increment"),
        ("Collect level up chest", "level_up_toggle", "level_up_increment"),
        ("Collect Bannerbox", "bannerbox_toggle", "bannerbox_increment"),
        (
            "Collect Trophy Rewards",
            "trophy_rewards_toggle",
            "trophy_rewards_increment",
        ),
    ],
    "Fight Jobs": [
        ("Fight trophy road battle", "trophy_road_toggle", None),
        ("Fight goblin queen battle", "goblin_queen_toggle", None),
        ("Fight path of legends battle", "legends_toggle", None),
        ("Fight 2v2 battle", "2v2_toggle", None),
        ("Fight war battle", "war_toggle", "war_increment"),
        ("Randomize deck", "randomize_deck_toggle", "randomize_deck_increment"),
        ("Random plays", "random_plays_toggle", None),
        ("Disable win/loss tracking", "disable_tracking_toggle", None),
        ("Skip fighting when full chests", "skip_battles_when_full_toggle", None),
    ],
}

botStatsDict = {
    "Bot Failures": 0,
    "Runtime": "00:00.00",
}
battleStatsDict = {
    "Wins": 0,
    "Losses": 0,
    "Win rate": 0,
    "Cards played": 0,
    "Path of legends fights": 0,
    "Trophy fights": 0,
    "Queens 1v1 fights": 0,
    "2v2 fights": 0,
    "War fights": 0,
    "Deck randomization": 0,
}
collectionStatsDict = {
    "Requests": 0,
    "Shop purchases": 0,
    "Donates": 0,
    "Chests unlocked": 0,
    "Daily rewards": 0,
    "Card mastery collects": 0,
    "Bannerbox collects": 0,
    "Cards upgraded": 0,
    "Battlepass collects": 0,
    "Level up collects": 0,
    "War chest collects": 0,
    "Season shop purchases": 0,
}
